blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'
urlpatterns = [
    path("", views.blog, name="blog_page"),
	path("<slug:slug>/", views.single_blog, name="single_blog"),

]

nrccnepal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('superadmin/', admin.site.urls),
    path('', include('core.urls')),
    path('blog/', include('blog.urls'), name='blog'),

] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.utils.text import slugify

# Create your models here.
def validate_if_between_1_10(value):
	if value <=10 and value >=0:
		return value
	else:
		raise ValidationError("This field only accepts integers between 0 and 10")

def validate_if_between_1_4(value):
	if value <=4 and value >=1:
		return value
	else:
		raise ValidationError("Values should be between 1 and 4 representing rows of Trending block")


class Authors(models.Model):
	author = models.CharField(max_length=100)
	description = models.CharField(max_length=1000)
	author_icon = models.ImageField(upload_to="images/test_uploads/", blank=True, null=True, default='default/no_image.jpg')
	mail = models.EmailField(max_length=200)
	joined_date = models.DateField()
	priority = models.IntegerField(default=0, validators=[validate_if_between_1_10])


	def __str__(self):
		return f"{self.author}"


class Blogs(models.Model):
	author = models.ForeignKey(Authors, on_delete=models.PROTECT)
	title = models.CharField("Blog Title", max_length=500)
	body = models.TextField(default="Type here...")
	published_date = models.DateField(auto_now_add=True, blank=True)
	updated_datetime = models.DateTimeField(auto_now=True, blank=True)
	priority = models.IntegerField(default=0, validators=[validate_if_between_1_10])
	# thumbnail = models.ImageField(upload_to="images/test_uploads/", blank=True, null=True, default='default/no_image.jpg')
	featured_image = models.ImageField(upload_to="images/test_uploads/", blank=True, null=True, default='default/no_image.jpg')
	# trending_priority = models.IntegerField(default=0, blank=True, validators=[validate_if_between_1_4])
	slug = models.SlugField(unique=True, max_length=600)

	def save(self):
		if not self.slug:
			self.slug = slugify(self.title)
		super().save()

	def __str__(self):
		return f"{self.title}"


class TrendingBlogs(models.Model):
	blogs = models.ForeignKey(Blogs, on_delete=models.CASCADE)
	priority = models.IntegerField(blank=False, null=False, unique=True, validators=[validate_if_between_1_4])

	def __str__(self):
		return f"{self.blogs.title}"


class UserComments(models.Model):
	blogs = models.ForeignKey(Blogs, on_delete=models.CASCADE)
	name = models.CharField(max_length=50)
	email = models.EmailField(max_length=200)
	message = models.TextField(default="Here goes your Comments...")
	date = models.DateField(auto_now_add=True, blank=True)

	def __str__(self):
		return f"Comments of {self.name}"

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, PageNotAnInteger
from django.template.defaultfilters import slugify
from .models import Blogs, TrendingBlogs


# Create your views here.

def blog(request):
	# Retriving the top blogs with highest priority
	trending_blogs = TrendingBlogs.objects.all().order_by('priority')

	all_blogs = Blogs.objects.all().order_by('priority','-updated_datetime','-published_date')
	paginator = Paginator(all_blogs, 4) # number of objects to display per page
	current_page = request.GET.get('page') # retreives current page number

	try:
		paginator_objects = paginator.page(current_page)
	except PageNotAnInteger:
		paginator_objects = paginator.page(1)

	return render(request, "blog/blog-page.html", {
		"blogs" : paginator_objects,
		"trending_blogs": trending_blogs,
		})


def single_blog(request, slug):
	# Retriving the top blogs with highest priority
	trending_blogs = TrendingBlogs.objects.all().order_by('priority')

	blog = Blogs.objects.filter(slug=slug).first()
	return render(request, "blog/single-blog.html", {
		"blog": blog,
		"trending_blogs": trending_blogs,
		})

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title></title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'blog/img/favicon.png' %}" rel="icon">
  <link href="{% static 'blog/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=EB+Garamond:wght@400;500&family=Inter:wght@400;500&family=Playfair+Display:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'blog/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'blog/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'blog/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
  <link href="{% static 'blog/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'blog/vendor/aos/aos.css' %}" rel="stylesheet">

  <!-- FOnt Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous"/>


  <!-- Template Main CSS Files -->
  <link href="{% static 'blog/css/variables.css' %}" rel="stylesheet">
  <link href="{% static 'blog/css/main.css' %}" rel="stylesheet">
</head>

<body>
  <!-- ======= Header ======= -->
  <header id="header" class="header d-flex align-items-center fixed-top">
    <div class="container-fluid container-xl d-flex align-items-center justify-content-between">

      <a href="#" class="logo d-flex align-items-center">
        <img src="{% static 'blog/img/logo.png' %}" alt="">
        <h1>NRCC</h1>
      </a>

      <nav id="navbar" class="navbar">
        <ul>
          <li><a href="#">Home</a></li>
          <li><a href="{% url 'blog:blog_page' %}">Blog</a></li>
          <li class="dropdown"><a href="#"><span>Programs</span> <i class="bi bi-chevron-down dropdown-indicator"></i></a>
            <ul>
              <li><a href="#">Read with NRCC</a></li>
              <li><a href="#">Research Talk</a></li>
              <li><a href="#">STEM Camp</a></li>
              <li><a href="#">Trainings</a></li>
            </ul>
          </li>

          <li><a href="#">About</a></li>
          <li><a href="#">Contact</a></li>
          <li><a href="{% url 'research' %}">Research</a></li>
          <li class="dropdown"><a href="#"><span>Get Involved</span> <i class="bi bi-chevron-down dropdown-indicator"></i></a>
            <ul>
              <li><a href="#">Puzzles</a></li>
              <li><a href="#">Donate</a></li>
            </ul>
          </li>
          <li><a href="#">What's New?</a></li>
        </ul>
      </nav>
      <!-- .navbar -->

      <div class="position-relative">
        <a href="#" class="mx-2"><span class="bi-twitter"></span></a>
        <a href="#" class="mx-2"><span class="bi-facebook"></span></a>
        <a href="#" class="mx-2"><span class="bi-instagram"></span></a>
        <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>

        <a href="#" class="mx-2 js-search-open"><span class="bi-search"></span></a>
        <i class="bi bi-list mobile-nav-toggle"></i>

        <!-- ======= Search Form ======= -->
        <div class="search-form-wrap js-search-form-wrap">
          <form action="search-result.html" class="search-form">
            <span class="icon bi-search"></span>
            <input type="text" placeholder="Search" class="form-control">
            <button class="btn js-search-close"><span class="bi-x"></span></button>
          </form>
        </div><!-- End Search Form -->

      </div>

    </div>

  </header><!-- End Header -->

  {% block body %}

  {% endblock %}

  <!-- ======= Footer ======= -->
  <footer id="footer" class="footer">
    <div class="footer-legal">
      <div class="container">

        <div class="row justify-content-between">
          <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
            <div class="copyright">
              Copyright &copy; 2023 <strong><span>NRCC</span></strong>. All Rights Reserved
            </div>
          </div>

          <div class="col-md-6">
            <div class="social-links mb-3 mb-lg-0 text-center text-md-end">
              <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
              <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
              <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
              <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
            </div>

          </div>

        </div>

      </div>
    </div>

  </footer>

  <a href="#" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'blog/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'blog/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'blog/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'blog/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'blog/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'blog/js/main.js' %}"></script>
</body>

blog/templates/blog/blog-page.html
{% extends 'blog/base.html' %}

{% load static %}

{% block body %}
<head>
  <title>NRCC Blogs</title>
</head> 
<body>
  <main id="main">
    <section>
      <div class="container">
        <div class="row">

          <div class="col-md-9" data-aos="fade-up">
            <h3 class="category-title">Category: 
              <span class="aside-tags list-unstyled">
                <li><a href="#">Business</a></li>
                <li><a href="#">Culture</a></li>
                <li><a href="#">Sport</a></li>
                <li><a href="#">Food</a></li>
                <li><a href="#">Politics</a></li>
                <li><a href="#">Celebrity</a></li>
                <li><a href="#">Startups</a></li>
                <li><a href="#">Travel</a></li>
              </span>
            </h3>

            {% for blog in blogs %}

            <div class="d-md-flex post-entry-2 half">
              <a href="{% url 'blog:single_blog' blog.title|slugify %}" class="me-4 thumbnail">
                <img src="{{ blog.featured_image.url }}" alt="" class="img-fluid">
              </a>
              <div>
                <div class="post-meta"><span class="date">Culture</span> <span class="mx-1">&bullet;</span> <span>{{ blog.published_date }}</span></div>
                <h3><a href="{% url 'blog:single_blog' blog.title|slugify %}">{{ blog.title }}</a></h3>
                <p>{{ blog.body|truncatewords:50 }}</p>
                <div class="d-flex align-items-center author">
                  <div class="photo"><img src="{% static 'blog/img/authors/person-2.jpg' %}" alt="" class="img-fluid"></div>
                  <div class="name">
                    <h3 class="m-0 p-0">{{ blog.author }}</h3>
                  </div>
                </div>
              </div>
            </div>

            {% endfor %}

            <div class="text-start py-4">
              <div class="custom-pagination">
                {% if blogs.has_previous %}
                <a href="?page={{ blogs.previous_page_number }}" class="prev">Previous</a>
                {% endif %}

                {% for i in blogs.paginator.page_range %}
                  {% if i == blogs.number  %}
                    <a href="?page={{ i }}" class="active">{{ i }}</a>
                  {% else %}
                    <a href="?page={{ i }}">{{ i }}</a>
                  {% endif %}
                {% endfor %}

                {% if blogs.has_next %}
                <a href="?page={{ blogs.next_page_number }}" class="next">Next</a>
                {% endif %}
              </div>
            </div>
          </div>

          <div class="col-md-3">
            <!-- ======= Sidebar ======= -->
            <div class="aside-block">

              <ul class="nav nav-pills custom-tab-nav mb-4" id="pills-tab" role="tablist">
                <li class="nav-item" role="presentation">
                  <button class="nav-link active" id="pills-trending-tab" data-bs-toggle="pill" data-bs-target="#pills-trending" type="button" role="tab" aria-controls="pills-trending" aria-selected="true">Trending</button>
                </li>
              </ul>

              <div class="tab-content" id="pills-tabContent">

                <!-- Trending -->
                <div class="tab-pane fade show active" id="pills-trending" role="tabpanel" aria-labelledby="pills-trending-tab">
                  {% for trending_blog in trending_blogs %}
                  <div class="post-entry-1 border-bottom">
                    <div class="post-meta"><span class="date">Sport</span> <span class="mx-1">&bullet;</span> <span>{{ trending_blog.blogs.published_date }}</span></div>
                    <h2 class="mb-2"><a href="{% url 'blog:single_blog' trending_blog.blogs.title|slugify %}">{{ trending_blog.blogs.title }}</a></h2>
                    <span class="author mb-3 d-block">{{ trending_blog.blogs.author }}</span>
                  </div>
                  </div>
                  {% endfor %}
                </div> <!-- End Trending -->

              </div>
            </div>
          </div>

        </div>
      </div>
    </section>
  </main><!-- End #main -->

</body>
{% endblock %}

blog/templates/blog/single-blog.html
{% extends 'blog/base.html' %}

{% load static %}

{% block body %}
<head>
  <title>NRCC Blogs</title>
</head> 
<body>
  <main id="main">

    <section class="single-post-content">
      <div class="container">
        <div class="row">
          <div class="col-md-9 post-content" data-aos="fade-up">

            <!-- ======= Single Post Content ======= -->
            <div class="single-post">
              <div class="post-meta"><span class="date">Business</span> <span class="mx-1">&bullet;</span> <span>{{ blog.published_date }}</span></div>
              <h1 class="mb-5">{{ blog.title }}</h1>

              <figure class="my-4">
                <img src="{{ blog.featured_image.url }}" alt="" class="img-fluid">
                <figcaption style="text-align: center;">Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo, odit? </figcaption>
              </figure>

              <p><span class="firstcharacter">{{ blog.body|slice:":1" }}</span>
                {{ blog.body|linebreaksbr|slice:"1:" }}
              </p>


              
            </div><!-- End Single Post Content -->

            <!-- ======= Comments ======= -->
            <div class="comments">
              <h5 class="comment-title py-4">2 Comments</h5>
              <div class="comment d-flex mb-4">
                <div class="flex-shrink-0">
                  <div class="avatar avatar-sm rounded-circle">
                    <img class="avatar-img" src="{% static 'blog/img/authors/person-5.jpg' %}" alt="" class="img-fluid">
                  </div>
                </div>
                <div class="flex-grow-1 ms-2 ms-sm-3">
                  <div class="comment-meta d-flex align-items-baseline">
                    <h6 class="me-2">Jordan Singer</h6>
                    <span class="text-muted">2d</span>
                  </div>
                  <div class="comment-body">
                    Lorem ipsum, dolor sit amet consectetur adipisicing elit. Non minima ipsum at amet doloremque qui magni, placeat deserunt pariatur itaque laudantium impedit aliquam eligendi repellendus excepturi quibusdam nobis esse accusantium.
                  </div>

                  <div class="comment-replies bg-light p-3 mt-3 rounded">
                    <h6 class="comment-replies-title mb-4 text-muted text-uppercase">2 replies</h6>

                    <div class="reply d-flex mb-4">
                      <div class="flex-shrink-0">
                        <div class="avatar avatar-sm rounded-circle">
                          <img class="avatar-img" src="{% static 'blog/img/authors/person-4.jpg' %}" alt="" class="img-fluid">
                        </div>
                      </div>
                      <div class="flex-grow-1 ms-2 ms-sm-3">
                        <div class="reply-meta d-flex align-items-baseline">
                          <h6 class="mb-0 me-2">Brandon Smith</h6>
                          <span class="text-muted">2d</span>
                        </div>
                        <div class="reply-body">
                          Lorem ipsum dolor sit, amet consectetur adipisicing elit.
                        </div>
                      </div>
                    </div>
                    <div class="reply d-flex">
                      <div class="flex-shrink-0">
                        <div class="avatar avatar-sm rounded-circle">
                          <img class="avatar-img" src="{% static 'blog/img/authors/person-3.jpg' %}" alt="" class="img-fluid">
                        </div>
                      </div>
                      <div class="flex-grow-1 ms-2 ms-sm-3">
                        <div class="reply-meta d-flex align-items-baseline">
                          <h6 class="mb-0 me-2">James Parsons</h6>
                          <span class="text-muted">1d</span>
                        </div>
                        <div class="reply-body">
                          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio dolore sed eos sapiente, praesentium.
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="comment d-flex">
                <div class="flex-shrink-0">
                  <div class="avatar avatar-sm rounded-circle">
                    <img class="avatar-img" src="{% static 'blog/img/authors/person-2.jpg' %}" alt="" class="img-fluid">
                  </div>
                </div>
                <div class="flex-shrink-1 ms-2 ms-sm-3">
                  <div class="comment-meta d-flex">
                    <h6 class="me-2">Santiago Roberts</h6>
                    <span class="text-muted">4d</span>
                  </div>
                  <div class="comment-body">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto laborum in corrupti dolorum, quas delectus nobis porro accusantium molestias sequi.
                  </div>
                </div>
              </div>
            </div><!-- End Comments -->

            <!-- ======= Comments Form ======= -->
            <div class="row justify-content-center mt-5">

              <div class="col-lg-12">
                <h5 class="comment-title">Leave a Comment</h5>
                <div class="row">
                  <div class="col-lg-6 mb-3">
                    <label for="comment-name">Name</label>
                    <input type="text" class="form-control" id="comment-name" placeholder="Enter your name">
                  </div>
                  <div class="col-lg-6 mb-3">
                    <label for="comment-email">Email</label>
                    <input type="text" class="form-control" id="comment-email" placeholder="Enter your email">
                  </div>
                  <div class="col-12 mb-3">
                    <label for="comment-message">Message</label>

                    <textarea class="form-control" id="comment-message" placeholder="Enter your name" cols="30" rows="10"></textarea>
                  </div>
                  <div class="col-12">
                    <input type="submit" class="btn btn-primary" value="Post comment">
                  </div>
                </div>
              </div>
            </div><!-- End Comments Form -->

          </div>
          <div class="col-md-3">
            <!-- ======= Sidebar ======= -->
            <div class="aside-block">

              <ul class="nav nav-pills custom-tab-nav mb-4" id="pills-tab" role="tablist">
                <li class="nav-item" role="presentation">
                  <button class="nav-link active" id="pills-trending-tab" data-bs-toggle="pill" data-bs-target="#pills-trending" type="button" role="tab" aria-controls="pills-trending" aria-selected="true">Trending</button>
                </li>
              </ul>

              <div class="tab-content" id="pills-tabContent">

                <div class="tab-pane fade show active" id="pills-trending" role="tabpanel" aria-labelledby="pills-trending-tab">
                  {% for trending_blog in trending_blogs %}
                  <div class="post-entry-1 border-bottom">
                    <div class="post-meta"><span class="date">Sport</span> <span class="mx-1">&bullet;</span> <span>{{ trending_blog.blogs.published_date }}</span></div>
                    <h2 class="mb-2"><a href="{% url 'blog:single_blog' trending_blog.blogs.title|slugify %}">{{ trending_blog.blogs.title }}</a></h2>
                    <span class="author mb-3 d-block">{{ trending_blog.blogs.author }}</span>
                  </div>
                  {% endfor %}
                   <!-- End Trending -->

              </div>
            </div>
            <div class="aside-block">
              <h3 class="aside-title">Tags</h3>
              <ul class="aside-tags list-unstyled">
                <li><a href="#">Business</a></li>
                <li><a href="#">Culture</a></li>
                <li><a href="#">Sport</a></li>
                <li><a href="#">Food</a></li>
                <li><a href="#">Politics</a></li>
                <li><a href="#">Celebrity</a></li>
                <li><a href="#">Startups</a></li>
                <li><a href="#">Travel</a></li>
              </ul>
            </div><!-- End Tags -->

          </div>
        </div>
      </div>
    </section>
  </main><!-- End #main -->
</body>
{% endblock %}